import os
import sys
import json
import shutil
import dspy
from pathlib import Path

# Fix Windows unicode printing
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
from dspy.teleprompt import COPRO
from agent.gepa_metric import gepa_metric

class AgentPrompt(dspy.Signature):
    """You are a helpful AI agent. Use your tools to solve the user's query."""
    user_query = dspy.InputField()
    trajectory = dspy.OutputField(desc="The thoughts, tool calls, and final response generated by the agent.")

class GEPA_Module(dspy.Module):
    def __init__(self, system_prompt: str):
        super().__init__()
        # In a real setup, this would invoke the actual agent. 
        # For DSPy optimization, we wrap it in a Predictor with the system prompt as instructions.
        self.predictor = dspy.Predict(AgentPrompt)
        
    def forward(self, user_query):
        return self.predictor(user_query=user_query)

def load_dataset(jsonl_path: str):
    dataset = []
    if not os.path.exists(jsonl_path):
        return dataset
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip(): continue
            try:
                data = json.loads(line)
                # Parse trajectory format
                # Extract user query and the final trajectory
                messages = data.get("conversations", [])
                user_query = ""
                trajectory = ""
                for msg in messages:
                    if msg.get("from") == "human" and not user_query:
                        user_query = msg.get("value")
                    else:
                        trajectory += f"[{msg.get('from')}]: {msg.get('value')}\n"
                
                if user_query:
                    dataset.append(dspy.Example(user_query=user_query, trajectory=trajectory).with_inputs('user_query'))
            except Exception as e:
                print(f"Error parsing line: {e}")
    return dataset

def run_gepa_pipeline():
    print("🚀 Starting GEPA Self-Evolution Pipeline (DSPy)")
    
    from dotenv import load_dotenv
    from pathlib import Path
    import os
    
    # Try local .env first, then ~/.hermes/.env
    load_dotenv(Path(".env"))
    load_dotenv(Path(os.path.expanduser("~/.hermes/.env")))
    
    # Configure DSPy LM
    # using gpt-4o as teacher/optimizer for now, assuming OPENAI_API_KEY is in env
    lm = dspy.LM("openai/gpt-4o", max_tokens=2048)
    dspy.settings.configure(lm=lm)
    
    # 1. Load Dataset
    trajectory_file = Path("trajectory_samples.jsonl")
    dataset = load_dataset(trajectory_file)
    if not dataset:
        print("⚠️ No dataset found or dataset is empty. Please run the agent with --save_trajectories to generate data.")
        return
        
    print(f"📚 Loaded {len(dataset)} trajectory examples for optimization.")
    
    # Train/Val split
    trainset = dataset[:int(len(dataset)*0.8)]
    valset = dataset[int(len(dataset)*0.8):]
    if not valset:
        valset = trainset # Fallback if dataset is too small
        
    # 2. Load current prompt
    soul_md_path = Path("SOUL.md")
    current_prompt = ""
    if soul_md_path.exists():
        with open(soul_md_path, "r", encoding="utf-8") as f:
            current_prompt = f.read()
    else:
        current_prompt = "You are a helpful AI agent."
        
    # 3. Optimize with COPRO
    print("🧬 Mutating prompts using DSPy COPRO...")
    module = GEPA_Module(system_prompt=current_prompt)
    
    copro_optimizer = COPRO(
        metric=gepa_metric,
        breadth=3,
        depth=2,
        init_temperature=0.7
    )
    
    try:
        optimized_module = copro_optimizer.compile(
            module,
            trainset=trainset,
            eval_kwargs={"num_threads": 4, "display_progress": True}
        )
    except Exception as e:
        print(f"❌ Optimization failed: {e}")
        return
        
    # 4. A/B Testing & Evaluation
    print("⚖️ Evaluating baseline vs GEPA-optimized module...")
    from dspy.evaluate import Evaluate
    evaluator = Evaluate(devset=valset, metric=gepa_metric, num_threads=4, display_progress=True, display_table=0)
    
    baseline_score = evaluator(module)
    optimized_score = evaluator(optimized_module)
    
    print(f"📊 Baseline Score: {baseline_score}")
    print(f"📊 Optimized Score: {optimized_score}")
    
    # 5. Auto-rollback / Save
    if optimized_score > baseline_score:
        print("✅ GEPA Optimization improved the score! Saving new SOUL.md...")
        if soul_md_path.exists():
            shutil.copy(soul_md_path, f"SOUL.md.bak_{int(os.path.getmtime(soul_md_path))}")
            
        # Extract the optimized prompt
        # In a real DSPy setup, we extract the instructions from the compiled predictor
        new_instructions = getattr(optimized_module.predictor.signature, '__doc__', optimized_module.predictor.signature.instructions)
        
        with open(soul_md_path, "w", encoding="utf-8") as f:
            f.write(new_instructions)
        print("💾 New prompt saved. Backup created.")
    else:
        print("🛑 GEPA Optimization degraded or didn't improve quality. Rolling back (no changes saved).")

if __name__ == "__main__":
    run_gepa_pipeline()
